version: 2.1
workflows:
 test-and-deploy:
   jobs:
     - test

jobs:
 test:
  docker:
      - image: cimg/node:22.7.0
  steps:
      - checkout
      - run:
         name: Install dependencies
         command: npm install
      - run:
          name: run Test
          command: npm run test
