version: 2.1
workflows: 
 workflow-1:
  jobs:
   - docker-test

jobs:
  docker-test:
   docker:
    image: cimg/node:22.7.0
   steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run: docker build .
    
