# version: 2.1
# workflows: 
#  workflow-1:
#   jobs:
#    - docker-test

# jobs:
#   docker-test:
#    docker:
#     - image: cimg/node:17.2-browsers
#    steps:
#     - checkout
#     - setup_remote_docker:
#         docker_layer_caching: true
#     - run: docker build .
    
version: 2.1

# executors:
#   default-executor:
#     docker:
#       - image: cimg/python:3.8  # This image is a good base for installing additional tools

jobs:
  trivy-scan:
    docker:
      - image: cimg/python:3.8 
    steps:
      - checkout # Checks out your source code
      - run:
          name: Update and Install curl, Trivy, and Helm
          command: |
            # Update package lists and install necessary packages
            sudo apt-get update && sudo apt-get install -y curl

            # Install Trivy
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.54.1

            # Install Helm
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | sudo bash
      - run:
          name: Verify Trivy Installation and Scan Files
          command: |
            # Verify Trivy installation
            trivy --version

            # Scan files in the current directory, including Helm charts
            # trivy fs --skip-files=.git,.github,.circleci --ignore-unfixed .
            trivy fs --severity HIGH,CRITICAL --exit-code 1 --ignore-unfixed -o trivy.json . || true
            # Check Trivy scan result
            if [ -s trivy.json ]; then
              echo "Trivy scan results:"
              cat trivy.json
            else
              echo "No vulnerabilities found or an error occurred."
            fi
      - store_artifacts:
          path: trivy.json
          destination: trivy.json
            
  semgrep-full-scan:
    docker:
      - image: semgrep/semgrep
    steps:
      - checkout
      - run:
          name: "Semgrep OSS full scan"
          command: semgrep ci --config auto --output semgrep.json    
      - store_artifacts:
          path: semgrep.json
          destination: semgrep.json

  gitleaks-scan:
    docker:
      - image: cimg/python:3.8 
    steps:
      - checkout
      - run:
          name: Install Gitleaks
          command: |
            curl -sSfL https://github.com/zricethezav/gitleaks/releases/download/v8.10.3/gitleaks-linux-amd64.tar.gz | tar -zx && sudo mv gitleaks-linux-amd64 /usr/local/bin/gitleaks
      - run:
          name: Run Gitleaks Scan for Secrets
          command: |
            gitleaks detect --source . --report-format json --report-path gitleaks-report.json

            if [ -s gitleaks-report.json ]; then
              echo "Gitleaks found leaks. Failing pipeline."
              cat gitleaks-report.json
              exit 1
            else
              echo "No leaks found by Gitleaks. Continuing pipeline."
            fi
      - store_artifacts:
          path: gitleaks-report.json
          destination: gitleaks-report.json
              
workflows:
  version: 2
  scan:
    jobs:
      - trivy-scan
      - gitleaks-scan
      - semgrep-full-scan






