version: 2.1
workflows: 
 workflow-1:
  jobs:
   - docker-test

jobs:
  docker-test:
   docker:
    - image: circleci/node:9.8.0-stretch-browsers
   steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run: docker build .
    
