# version: 2.1
# workflows: 
#  workflow-1:
#   jobs:
#    - docker-test

# jobs:
#   docker-test:
#    docker:
#     - image: cimg/node:17.2-browsers
#    steps:
#     - checkout
#     - setup_remote_docker:
#         docker_layer_caching: true
#     - run: docker build .
    
version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/python:3.8  # This image is a good base for installing additional tools

jobs:
  trivy-scan:
    executor: default-executor
    steps:
      - checkout # Checks out your source code
      - run:
          name: Update and Install curl, Trivy, and Helm
          command: |
            # Update package lists and install necessary packages
            sudo apt-get update && sudo apt-get install -y curl

            # Install Trivy
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.18.3

            # Install Helm
            curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | sudo bash
      - run:
          name: Verify Trivy Installation and Scan Files
          command: |
            # Verify Trivy installation
            trivy --version

            # Scan files in the current directory, including Helm charts
            # trivy fs --skip-files=.git,.github,.circleci --ignore-unfixed .
            trivy config --severity HIGH,CRITICAL ./package.json
              
workflows:
  version: 2
  scan:
    jobs:
      - trivy-scan






